export const state = {
  userId: '',
  userName: '',
  accessToken: '',
  roomId: '',
  ws: null,
  lastSequence: 0,
  orgId: '',
  workspaceId: '',
  agentTemplates: [],
  roomAgents: [],
  allRoomOutputs: [],
  roomOutputs: [],
  currentBranchId: '',
  currentBranchMode: '',
  currentTurnLock: null,
  roomOntology: {entities: [], relationships: [], reviews: []},
  currentRoomRole: 'viewer',
  currentRoomName: '',
  myRooms: [],
  roomMembers: [],
  roomBranches: [],
  roomRuns: [],
  openThreadRootId: '',
  threadReplyTargetId: '',
  readCursor: 0,
  selectedArtifactId: '',
  sessionMode: '', // '' | 'bearer' | 'cookie'
  ssoConfig: {sso: false, provider_label: 'single sign-on', demo: false},
  cookieRedirecting: false,
  wasAboveMobileBreak: window.innerWidth > 860,
  modalOpenerElement: null,
  pendingDialogResolve: null,
  roomUnreadCounts: new Map(),
  wsReconnectDelay: 1000,
  wsReconnectAttempts: 0,
  wsReconnectTimer: null,
  wsRoomId: null,
  loadStatePromise: null,
  loadStatePromiseRoom: null,
  staleCallDuringLoad: false,
  pendingEventsDuringLoad: [],
  lastNotifications: [],
  autoReadTimer: null,
  lastArtifacts: [],
  lastDecisions: [],
  synthesisTitleAuto: '',
  // messageId -> outputId: which message's "Full output" record is
  // currently open, so a message re-render (a reaction, any snapshot
  // reconcile) can re-include the same record from data instead of the
  // open panel depending on a DOM node the render pipeline knows nothing
  // about surviving by accident.
  openOutputRecords: new Map(),
};
